# Generated by Django 3.1.1 on 2020-12-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='Date creation')),
                ('update_date', models.DateTimeField(verbose_name='Date update')),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(default='Description here')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(default='Description here')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(verbose_name='Date creation')),
                ('update_date', models.DateTimeField(verbose_name='Date update')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category')),
                ('id_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.vendor')),
            ],
        ),
    ]
