# Generated by Django 3.1.1 on 2020-10-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
            ],
        ),
    ]
